server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: roommanagement
          uri: http://RoomManagement:8080
          predicates:
            - Path=/RoomManagement/**
        - id: reservationmanagement
          uri: http://ReservationManagement:8080
          predicates:
            - Path=/ReservationManagement/**
        - id: paymentmanagement
          uri: http://PaymentManagement:8080
          predicates:
            - Path=/PaymentManagement/**
